apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: examples
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:eduardo-mdc/Rafael-Homelab.git
    targetRevision: HEAD
    path: kubernetes/deployments/examples
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
