apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: examples
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rafael-homelab
  source:
    repoURL: git@github.com:eduardo-mdc/Rafael-Homelab.git
    targetRevision: HEAD
    path: kubernetes/deployments/examples
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: rafael-homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
