apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portfolio-media
  namespace: rafael-homelab
  labels:
    app.kubernetes.io/name: portfolio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
